name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots verify
          mvn cobertura:cobertura -Dcobertura.report.format=xml
      - name : Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          files: ./target/site/cobertura/coverage.xml