name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots verify
      - name: Generate coverage report
        run: mvn jacoco:report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          files: ./mundo-core/target/site/jacoco/jacoco.xml,./mundo-xml/target/site/jacoco/jacoco.xml,./mundo-process/target/site/jacoco/jacoco.xml,./spring-boot-starter-mundo/target/site/jacoco/jacoco.xml,./target/site/jacoco-aggregate/jacoco.xml